inlineStock_rs/Controllers/ManagementsController.cs
using inlineStock_rs.Models;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace inlineStock_rs.Controllers
{
    public class ManagementsController : Controller
    {
        MATERIAL_STOCKEntities1 db = new MATERIAL_STOCKEntities1(); // declare goaldbal Database

        // GET: Managements
        public ActionResult managements_overview()
        {
            return View();
        }

        //dicing
        [HttpGet]
        public ActionResult managements_adjust_actual_dicing()
        {
            List<tb_NEvent> model = new List<tb_NEvent>();
            using (MATERIAL_STOCKEntities1 dc = new MATERIAL_STOCKEntities1())
            {
                model = dc.tb_NEvent.ToList();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult managements_adjust_actual_dicing(List<tb_NEvent> list)
        {
            if (ModelState.IsValid)
            {
                using (MATERIAL_STOCKEntities1 dc = new MATERIAL_STOCKEntities1())
                {
                    foreach (var i in list)
                    {
                        var c = dc.tb_NEvent.Where(a => a.MATCODE.Equals(i.MATCODE)).FirstOrDefault();
                        if (c != null)
                        {
                            c.REMAIN_INLINE = i.REMAIN_INLINE;
                            c.PURPOSE_DETAIL = "RESET";

                        }
                    }
                    dc.SaveChanges();
                }
                ViewBag.Message = "Successfully Updated.";
                return View(list);
            }
            else
            {
                ViewBag.Message = "Failed ! Please try again.";
                return View(list);
            }
        }

        //CG
        public ActionResult managements_adjust_actual_cg()
        {
            return View();
        }

        public ActionResult ajax_get_managements_adjust_actual_cg()
        {
            var data = db.tb_NEvent_CG.ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult update_adjust_end_month_cg(tb_NEvent_CG edit_value)
        {
            string cnnString = System.Configuration.ConfigurationManager.ConnectionStrings["dbinlineEntities2"].ConnectionString;
            SqlConnection cnn = new SqlConnection(cnnString);
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnn;
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "sp_adjust_eomonth";
            cmd.Parameters.AddWithValue("@MATCODE", edit_value.MATCODE);
            cmd.Parameters.AddWithValue("@ITEM_NUMBER", edit_value.ITEM_NUMBER);
            cmd.Parameters.AddWithValue("@COST_CENTER", edit_value.COST_CENTER);
            cmd.Parameters.AddWithValue("@REMAIN_INLINE", edit_value.REMAIN_INLINE);
            cmd.Parameters.AddWithValue("@FLAG_MAT", edit_value.FLAG_MAT);
            cmd.Parameters.AddWithValue("@UPDATE_BY", edit_value.UPDATE_BY);

            cnn.Open();
            object o = cmd.ExecuteNonQuery();
            cnn.Close();
            return new EmptyResult();
        }

        //ASSY
        public ActionResult managements_adjust_actual_assy()
        {
            return View();
        }

        public ActionResult ajax_get_managements_adjust_actual_assy()
        {
            var data = db.tb_NEvent_ASSY.ToList()
                     .Where(a => a.MATNAME != "-")
                    .OrderByDescending(x => x.MATGROUP); ;
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        //JUNB
        public ActionResult managements_adjust_actual_junb()
        {
            return View();
        }

        public ActionResult ajax_get_managements_adjust_actual_junb()
        {
            var data = db.sp_display_junb_main().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }
      
        //CSAT
        public ActionResult managements_adjust_actual_csat()
        {
            return View();
        }

        public ActionResult ajax_get_managements_adjust_actual_csat()
        {
            var data = db.sp_display_CSAT().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        //M-OLED
        public ActionResult managements_adjust_actual_moled()
        {
            return View();
        }

        public ActionResult ajax_get_managements_adjust_actual_moled()
        {
            var data = db.sp_display_moled().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        // HTPS
        public ActionResult managements_adjust_actual_htps()
        {
            return View();
        }

        public ActionResult ajax_get_managements_adjust_actual_htps()
        {
            //var data = db.tb_NEvent_HTPS.ToList();
            //var data = (from a in db.tb_NEvent_HTPS
            //              leftjoin b in db.tb_formula_factor 
            //            on new { p1=a.MATCODE , p2=a.ITEM_NUMBER } equals new {p1=b.MATCODE, p2=b.ITEM_NUMBER }                        
            //            select new { a.MATGROUP, a.MATCODE, a.ITEM_NUMBER, a.MATNAME, a.REMAIN_INLINE, b.UNIT }).Distinct();

            // var data = from u in db.tb_NEvent_HTPS
            //            join p in db.tb_formula_factor.Where(x => x.FLAG_MAT == "HTPS")
            //    on u.MATCODE equals p.MATCODE
            //into temp
            //            from j in temp.DefaultIfEmpty()
            //            select new
            //            {
            //                BIZ_NAME = u.BIZ_NAME,

            //                FLAG_MAT = u.FLAG_MAT,

            //                MATGROUP = u.MATGROUP,
            //                MATCODE = u.MATCODE,
            //                ITEM_NUMBER = u.ITEM_NUMBER,
            //                MATNAME = u.MATNAME,
            //                REMAIN_INLINE = u.REMAIN_INLINE,
            //                UNIT = j.UNIT ?? u.UNIT
            //            };
            var data = db.sp_display_adjust_htps().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Upload_excel_taget_junb_csat()
        {
            return View();
        }

        // Upload Excel target data
        public ActionResult clear_information_target()
        {
            db.Database.ExecuteSqlCommand("DELETE FROM tb_temp_junb_csat_target DBCC CHECKIDENT('tb_temp_junb_csat_target', RESEED, 0)"); // reset identity in sqlserver
            string message = "Welcome";
            return new JsonResult { Data = message, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    
        [HttpPost]
        public ActionResult Upload_excel_target(FormCollection formCollection, string valueINeeds)
        {
            try
            {
                var tb_temp_junb_csat_target_LIST = new List<tb_temp_junb_csat_target>();

                if (Request != null)
                {
                    HttpPostedFileBase file = Request.Files["UploadedFile_junb_csat"];
                    if ((file != null) && (file.ContentLength > 0) && !string.IsNullOrEmpty(file.FileName))
                    {
                        string fileName = file.FileName;
                        string fileContentType = file.ContentType;
                        byte[] fileBytes = new byte[file.ContentLength];
                        var data = file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));
                        ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                        using (var package = new ExcelPackage(file.InputStream))
                        {
                            var currentSheet = package.Workbook.Worksheets;
                            var workSheet = package.Workbook.Worksheets["For Adj & Upload"];
                            var noOfCol = workSheet.Dimension.End.Column;
                            //var noOfRow = workSheet.Dimension.End.Row;
                            var noOfRow = workSheet.Cells.Where(cell => !string.IsNullOrEmpty(cell.Value?.ToString() ?? string.Empty)).LastOrDefault().End.Row;

                            for (int rowIterator = 5; rowIterator <= noOfRow; rowIterator++)
                            {
                                // tager information
                                var data_temp_junb_csat_target = new tb_temp_junb_csat_target();


                                //data_temp_junb_csat_target.PROCESS = workSheet.Cells[rowIterator, 3]?.Value?.ToString();//IS CG M-OLED
                                //data_temp_junb_csat_target.ITEM_NUMBER = workSheet.Cells[rowIterator, 7]?.Value?.ToString();//IS CG M-OLED
                                //data_temp_junb_csat_target.MATERIAL_TYPE = workSheet.Cells[rowIterator, 2]?.Value?.ToString();//IS CG M-OLED
                                //data_temp_junb_csat_target.COST_CENTER = workSheet.Cells[rowIterator, 6]?.Value?.ToString();//IS CG M-OLED
                                //data_temp_junb_csat_target.ISSUE_TARGET = workSheet.Cells[rowIterator, 36]?.Value?.ToString();//IS CG M-OLED

                                //data_temp_junb_csat_target.ITEM_NUMBER = workSheet.Cells[rowIterator, 6]?.Value?.ToString(); //LSI
                                //data_temp_junb_csat_target.COST_CENTER = workSheet.Cells[rowIterator, 3]?.Value?.ToString(); // LSI
                                //data_temp_junb_csat_target.ISSUE_TARGET = workSheet.Cells[rowIterator, 37]?.Value?.ToString(); //LSI

                                data_temp_junb_csat_target.PROCESS = workSheet.Cells[rowIterator, 4]?.Value?.ToString();//HTPS

inlineStock_rs/Views/Managements/managements_adjust_actual_dicing.cshtml
@model List<inlineStock_rs.Models.tb_NEvent>
@{
    ViewBag.Title = "";
}
@if (Session["GOALBAL_ID"] != null)
{
    <style>
        .table th, td {
            color: black;
        }

        table.center-all td, th {
            text-align: center;
        }

        td.highlight_7212 {
            background-color: deeppink;
            font-weight: bold;
            color: white;
        }

        highlight_7213 {
            background-color: blue;
            font-weight: bold;
            color: white;
        }
    </style>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center border-bottom mt-3">
        <h5 class="mr-2"> Fucntion Adjust data End of Month</h5>
    </div>

    <div class="table-responsive">
        @using (Ajax.BeginForm("managements_adjust_actual_dicing", "Managements", new AjaxOptions { OnSuccess = "OnSuccess", OnFailure = "OnFailure", LoadingElementId = "progress" }))
        {
            <table class="table table-hover table-bordered mb-0" id="inline_dicing_adjust">
                <thead>
                    <tr>
                        <th scope="col" style="background-color:royalblue;color:white;">MATERIAL CODE</th>
                        <th scope="col" style="background-color:royalblue;color:white;">ITEM NUMBER</th>
                        <th scope="col" style="background-color:royalblue;color:white;">MATERIAL NAME</th>
                        <th scope="col" style="background-color:royalblue;color:white;">MATERIAL GROUP</th>
                        <th scope="col" style="background-color:royalblue;color:white;">COST CENTER</th>
                        <th scope="col" style="background-color:royalblue;color:white;">REMAIN INLINE</th>
                        <th scope="col" style="background-color:royalblue;color:white;">UNIT</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        <tr>
                            @if (Model[i].COST_CENTER == "7213")
                            {
                                <td>@Html.DisplayFor(model => model[i].MATCODE, new { htmlAttributes = new { @class = "text-center", @readonly = "" } })</td>
                                <td>@Html.DisplayFor(model => model[i].ITEM_NUMBER, new { htmlAttributes = new { @class = "text-center", @readonly = "" } })</td>
                                <td>@Html.DisplayFor(model => model[i].MATNAME, new { htmlAttributes = new { @class = "", @readonly = "" } })</td>
                                <td>@Html.DisplayFor(model => model[i].MATGROUP, new { htmlAttributes = new { @class = "text-center", @readonly = "" } })</td>
                                <td>@Html.DisplayFor(model => model[i].COST_CENTER, new { htmlAttributes = new { @class = "highlight_7213 text-center", @readonly = "" } })</td>
                                <td>@Html.EditorFor(model => model[i].REMAIN_INLINE, new { htmlAttributes = new { @class = "text-center" } })</td>
                                <td>@Html.DisplayFor(model => model[i].Unit, new { htmlAttributes = new { @class = "text-center", @readonly = "" } })</td>

                                @Html.HiddenFor(model => model[i].MATCODE, new { htmlAttributes = new { @class = "", @readonly = "" } }) <!-- Hidden -->
                                @Html.HiddenFor(model => model[i].ITEM_NUMBER, new { htmlAttributes = new { @class = "", @readonly = "" } }) <!-- Hidden -->
                                @Html.HiddenFor(model => model[i].MATNAME, new { htmlAttributes = new { @class = "", @readonly = "" } }) <!-- Hidden -->
                                @Html.HiddenFor(model => model[i].MATGROUP, new { htmlAttributes = new { @class = "text-center", @readonly = "" } }) <!-- Hidden -->
                                @Html.HiddenFor(model => model[i].COST_CENTER, new { htmlAttributes = new { @class = "text-center", @readonly = "" } }) <!-- Hidden -->
                                @Html.HiddenFor(model => model[i].Unit, new { htmlAttributes = new { @class = "text-center", @readonly = "" } }) <!-- Hidden -->

                            }

                            @if (Model[i].COST_CENTER == "7212")
                            {
                                <td>@Html.DisplayFor(model => model[i].MATCODE, new { htmlAttributes = new { @class = "text-center", @readonly = "" } })</td>
                                <td>@Html.DisplayFor(model => model[i].ITEM_NUMBER, new { htmlAttributes = new { @class = "text-center", @readonly = "" } })</td>
                                <td>@Html.DisplayFor(model => model[i].MATNAME, new { htmlAttributes = new { @class = "", @readonly = "" } })</td>
                                <td>@Html.DisplayFor(model => model[i].MATGROUP, new { htmlAttributes = new { @class = "text-center", @readonly = "" } })</td>
                                <td>@Html.DisplayFor(model => model[i].COST_CENTER, new { htmlAttributes = new { @class = "text-center", @readonly = "" } })</td>
                                <td>@Html.EditorFor(model => model[i].REMAIN_INLINE, new { htmlAttributes = new { @class = "text-center" } })</td>
                                <td>@Html.DisplayFor(model => model[i].Unit, new { htmlAttributes = new { @class = "text-center", @readonly = "" } })</td>

                                @Html.HiddenFor(model => model[i].MATCODE, new { htmlAttributes = new { @class = "", @readonly = "" } }) <!-- Hidden -->
                                @Html.HiddenFor(model => model[i].ITEM_NUMBER, new { htmlAttributes = new { @class = "", @readonly = "" } }) <!-- Hidden -->
                                @Html.HiddenFor(model => model[i].MATNAME, new { htmlAttributes = new { @class = "", @readonly = "" } }) <!-- Hidden -->
                                @Html.HiddenFor(model => model[i].MATGROUP, new { htmlAttributes = new { @class = "text-center", @readonly = "" } }) <!-- Hidden -->
                                @Html.HiddenFor(model => model[i].COST_CENTER, new { htmlAttributes = new { @class = "text-center", @readonly = "" } }) <!-- Hidden -->
                                @Html.HiddenFor(model => model[i].Unit, new { htmlAttributes = new { @class = "text-center", @readonly = "" } }) <!-- Hidden -->
                            }


                        </tr>
                    }
                </tbody>
            </table>
            <div style="text-align: center; margin-top:10px; margin-bottom:10px;">
                <button type="submit" class="btn  btn-sm btn-primary" id="save_all">SAVE DATA</button>
            </div>
        }
    </div>

    <script>
        $(document).ready(function () {
            function OnSuccess(response) {
                alert("Update information success");
            }
            function OnFailure(response) {
                alert("Error occured.");
            }
            var table = $('#inline_dicing_adjust').dataTable({
                "destroy": true,
                "searching": false,
                "lengthChange": false,
                "paging": false,
                "bInfo": false,
                "stateSave": false,
                "scrollY": '70vh',
                "scrollCollapse": true,
                "lengthChange": false,
                columnDefs: [
                    { targets: [0, 1, 3, 4, 5, 6], className: 'text-center' },
                ],
            });
        });
    </script>
}
else
{
    Response.Redirect("~/Login/Login");
}

inlineStock_rs/Views/Managements/managements_overview.cshtml
<link rel="stylesheet" href="~/Content/overview-custom.css">

<div class="container bg-light rounded">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center text-center ">
        <div class="h5 font-weight-bold text-center py-3">MANAMENT SYSTEM</div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-sm-6 my-lg-0 my-3">
            <div class="box bg-white shadow border" id="box_aurten">
                <div class="d-flex align-items-center">
                    <div class="d-flex flex-column">
                        <b>Authentication</b> <a>
                            <p class="text-muted">Management</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 my-lg-0 my-3">
            <div class="box bg-white shadow border" id="box_upload_target">
                <div class="d-flex align-items-center">
                    <div class="d-flex flex-column">
                        <b>Upload data</b> <a href="#">
                            <p class="text-muted">Management</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 my-lg-0 my-3">
            <div class="box bg-white shadow border" id="box_cfactor">
                <div class="d-flex align-items-center">
                    <div class="d-flex flex-column">
                        <b>Controls Factor</b> <a href="#">
                            <p class="text-muted">Management</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center  text-center mt-3 ">
        <div class="h5 font-weight-bold text-center py-3">ADJUST END OF MONTH (IS)</div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-sm-6 my-lg-0 my-3">
            <div class="box bg-white shadow border" id="box_adjust_dicing">
                <div class="d-flex align-items-center">
                    <div class="d-flex flex-column">
                        <b>PROCESS : DICING</b> <a>
                            <p class="text-muted">MATERIALS</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 my-lg-0 my-3">
            <div class="box bg-white shadow border" id="box_adjust_cg">
                <div class="d-flex align-items-center">
                    <div class="d-flex flex-column">
                        <b>PROCESS : CG</b> <a>
                            <p class="text-muted">MATERIALS</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 my-lg-0 my-3">
            <div class="box bg-white shadow border" id="box_adjust_assy">
                <div class="d-flex align-items-center">
                    <div class="d-flex flex-column">
                        <b>PROCESS : ASSY</b> <a href="#">
                            <p class="text-muted">MATERIALS</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 my-lg-3 my-3">
            <div class="box bg-white shadow border" id="box_adjust_junb">
                <div class="d-flex align-items-center">
                    <div class="d-flex flex-column">
                        <b>PROCESS : JUNB</b> <a href="#">
                            <p class="text-muted">MATERIALS</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 my-lg-3 my-3">
            <div class="box bg-white shadow border" id="box_adjust_csat">
                <div class="d-flex align-items-center">
                    <div class="d-flex flex-column">
                        <b>PROCESS : CSAT</b> <a href="#">
                            <p class="text-muted">MATERIALS</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center  text-center mt-3 ">
        <div class="h5 font-weight-bold text-center py-3">ADJUST END OF MONTH (DD)</div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-sm-6 my-lg-3 my-3">
            <div class="box bg-white shadow border" id="box_adjust_htps">
                <div class="d-flex align-items-center">
                    <div class=" d-flex align-items-center justify-content-center"></div>
                    <div class="d-flex flex-column">
                        <b>HTPS</b> <a href="#">
                            <p class="text-muted">MATERIALS</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 my-lg-3 my-3">
            <div class="box bg-white shadow border" id="box_adjust_moled">
                <div class="d-flex align-items-center">
                    <div class=" d-flex align-items-center justify-content-center"></div>
                    <div class="d-flex flex-column">
                        <b>M-OLED</b> <a href="#">
                                          <p class="text-muted">MATERIALS</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#box_adjust_dicing").click(function () {
            window.location.href = "@Url.Action("managements_adjust_actual_dicing", "Managements")";
        });
        $("#box_adjust_cg").click(function () {
            window.location.href = "@Url.Action("managements_adjust_actual_cg", "Managements")";
        });
        $("#box_adjust_assy").click(function () {
            window.location.href = "@Url.Action("managements_adjust_actual_assy", "Managements")";
        });
        $("#box_adjust_junb").click(function () {
            window.location.href = "@Url.Action("managements_adjust_actual_junb", "Managements")";
        });
        $("#box_adjust_csat").click(function () {
            window.location.href = "@Url.Action("managements_adjust_actual_csat", "Managements")";
        });
         $("#box_adjust_moled").click(function () {
            window.location.href = "@Url.Action("managements_adjust_actual_moled", "Managements")";
         });
         $("#box_adjust_htps").click(function () {
            window.location.href = "@Url.Action("managements_adjust_actual_htps", "Managements")";
        });
        $("#box_upload_target").click(function () {
            window.location.href = "@Url.Action("Upload_excel_taget_junb_csat", "Managements")"; 
        });
        $("#box_cfactor").click(function () {
            window.location.href = "@Url.Action("managements_control_factor", "Managements")";
        });
    });
</script>