inlineStock_rs/Controllers/InlineStockController.cs
using inlineStock_rs.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace inlineStock_rs.Controllers
{
    public class InlineStockController : Controller
    {
        MATERIAL_STOCKEntities1 db = new MATERIAL_STOCKEntities1(); // declare goalbal Database

        // GET: InlineStock

        public ActionResult inline_home()
        {
            return View();
        }
        public ActionResult overview_records()
        {
            return View();
        }
        
        // DICING
        public ActionResult Oparate_inline_dicing()
        {
            Ajax_Get();
            return View();
        }

        public ActionResult Ajax_Get()
        {
            var data = db.sp_master_table().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Ajax_show()
        {
            var data = db.tb_NEvent.ToList().OrderByDescending(x => x.COST_CENTER);
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CU(tb_NEvent edit_value)
        {
            string cnnString = System.Configuration.ConfigurationManager.ConnectionStrings["dbinlineEntities2"].ConnectionString;
            SqlConnection cnn = new SqlConnection(cnnString);
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnn;
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "sp_add_usage";
            cmd.Parameters.AddWithValue("@BIZ_NAME", edit_value.BIZ_NAME);
            cmd.Parameters.AddWithValue("@MATCODE", edit_value.MATCODE);
            cmd.Parameters.AddWithValue("@ITEM_NUMBER", edit_value.ITEM_NUMBER);
            cmd.Parameters.AddWithValue("@MATNAME", edit_value.MATNAME);
            cmd.Parameters.AddWithValue("@MATGROUP", edit_value.MATGROUP);
            cmd.Parameters.AddWithValue("@COST_CENTER", edit_value.COST_CENTER);
            cmd.Parameters.AddWithValue("@FLAG_MAT", edit_value.FLAG_MAT);
            cmd.Parameters.AddWithValue("@ISSUE_WH", edit_value.ISSUE_WH);
            cmd.Parameters.AddWithValue("@STOCK_WH", edit_value.STOCK_WH);
            cmd.Parameters.AddWithValue("@USAGE", edit_value.USAGE);
            cmd.Parameters.AddWithValue("@REMAIN_INLINE", edit_value.REMAIN_INLINE);
            cmd.Parameters.AddWithValue("@UPDATE_DATE", edit_value.UPDATE_DATE);
            cmd.Parameters.AddWithValue("@PURPOSE_DETAIL", edit_value.PURPOSE_DETAIL);
            cmd.Parameters.AddWithValue("@UPDATE_BY", edit_value.UPDATE_BY);
            cnn.Open();
            object o = cmd.ExecuteNonQuery();
            cnn.Close();
            return new EmptyResult();
        }
        
        // ASSY
        public ActionResult Oparate_inline_assy()
        {
            return View();
        }

        public ActionResult ajax_get_assy()
        {
            var data = db.sp_master_table().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ajax_show_assy()
        {
            var data = db.tb_NEvent_ASSY.ToList()
                    .Where(a => a.MATNAME != "-")
                    .OrderByDescending(x => x.MATGROUP);
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        // ASSY tablet
        public ActionResult Oparate_inline_assy_tablet()
        {
           // ajax_get_assy();
            return View();
        }

        public ActionResult Oparate_inline_assy_menu_tablet()
        {
            return View();
        }

        //JUNB 
        public ActionResult Oparate_inline_junb_view()
        {
            ajax_get_junb();
            return View();
        }

        public ActionResult Oparate_inline_junb()
        {
            //ajax_show_junb_master();
            ajax_get_junb();
            return View();
        }

        public ActionResult ajax_get_junb()
        {
            var data = db.sp_master_table().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ajax_show_junb()
        {
            var data = db.sp_display_JUNB().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ajax_show_junb_master()
        {
            var data = db.sp_display_junb_main().ToList().OrderByDescending(x => x.MATGROUP);
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        //public ActionResult update_usage_junb(tb_NEvent_JUNBS edit_value)
        //{
        //    string cnnString = System.Configuration.ConfigurationManager.ConnectionStrings["dbinlineEntities2"].ConnectionString;
        //    SqlConnection cnn = new SqlConnection(cnnString);
        //    SqlCommand cmd = new SqlCommand();
        //    cmd.Connection = cnn;
        //    cmd.CommandType = System.Data.CommandType.StoredProcedure;
        //    cmd.CommandText = "sp_add_usage_junb";
        //    cmd.Parameters.AddWithValue("@BIZ_NAME", edit_value.BIZ_NAME);
        //    cmd.Parameters.AddWithValue("@MATCODE", edit_value.MATCODE);
        //    cmd.Parameters.AddWithValue("@ITEM_NUMBER", edit_value.ITEM_NUMBER);
        //    cmd.Parameters.AddWithValue("@MATNAME", edit_value.MATNAME);
        //    cmd.Parameters.AddWithValue("@MATGROUP", edit_value.MATGROUP);
        //    //cmd.Parameters.AddWithValue("@COST_CENTER", edit_value.COST_CENTER);
        //    cmd.Parameters.AddWithValue("@FLAG_MAT", edit_value.FLAG_MAT);
        //    cmd.Parameters.AddWithValue("@ISSUE_WH", edit_value.ISSUE_WH);
        //    cmd.Parameters.AddWithValue("@STOCK_WH", edit_value.STOCK_WH);
        //    cmd.Parameters.AddWithValue("@USAGE", edit_value.USAGE);
        //    cmd.Parameters.AddWithValue("@REMAIN_INLINE", edit_value.REMAIN_INLINE);
        //    cmd.Parameters.AddWithValue("@UPDATE_DATE", edit_value.UPDATE_DATE);
        //    cmd.Parameters.AddWithValue("@PURPOSE_DETAIL", edit_value.PURPOSE_DETAIL);
        //    cmd.Parameters.AddWithValue("@UPDATE_BY", edit_value.UPDATE_BY);
        //    cnn.Open();
        //    object o = cmd.ExecuteNonQuery();
        //    cnn.Close();
        //    return new EmptyResult();
        //}

        // CSAT
        public ActionResult Oparate_inline_csat_view()
        {
            ajax_get_csat();
            return View();
        }

        public ActionResult Oparate_inline_csat()
        {
            ajax_get_csat();
            return View();
        }

        public ActionResult ajax_get_csat()
        {
            var data = db.sp_master_table().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ajax_show_csat()
        {
            var data = db.sp_display_CSAT().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        //public ActionResult update_usage_csat(tb_NEvent_CSAT edit_value)
        //{
        //    string cnnString = System.Configuration.ConfigurationManager.ConnectionStrings["dbinlineEntities2"].ConnectionString;
        //    SqlConnection cnn = new SqlConnection(cnnString);
        //    SqlCommand cmd = new SqlCommand();
        //    cmd.Connection = cnn;
        //    cmd.CommandType = System.Data.CommandType.StoredProcedure;
        //    cmd.CommandText = "sp_add_usage_csat";
        //    cmd.Parameters.AddWithValue("@BIZ_NAME", edit_value.BIZ_NAME);
        //    cmd.Parameters.AddWithValue("@MATCODE", edit_value.MATCODE);
        //    cmd.Parameters.AddWithValue("@ITEM_NUMBER", edit_value.ITEM_NUMBER);
        //    cmd.Parameters.AddWithValue("@MATNAME", edit_value.MATNAME);
        //    cmd.Parameters.AddWithValue("@MATGROUP", edit_value.MATGROUP);
        //    cmd.Parameters.AddWithValue("@COST_CENTER", edit_value.COST_CENTER);
        //    cmd.Parameters.AddWithValue("@FLAG_MAT", edit_value.FLAG_MAT);
        //    cmd.Parameters.AddWithValue("@ISSUE_WH", edit_value.ISSUE_WH);
        //    cmd.Parameters.AddWithValue("@STOCK_WH", edit_value.STOCK_WH);
        //    cmd.Parameters.AddWithValue("@USAGE", edit_value.USAGE);
        //    cmd.Parameters.AddWithValue("@REMAIN_INLINE", edit_value.REMAIN_INLINE);
        //    cmd.Parameters.AddWithValue("@UPDATE_DATE", edit_value.UPDATE_DATE);
        //    cmd.Parameters.AddWithValue("@PURPOSE_DETAIL", edit_value.PURPOSE_DETAIL);
        //    cmd.Parameters.AddWithValue("@UPDATE_BY", edit_value.UPDATE_BY);
        //    cnn.Open();
        //    object o = cmd.ExecuteNonQuery();
        //    cnn.Close();
        //    return new EmptyResult();
        //}


        // CG
        public ActionResult Oparate_inline_cg()
        {
            ajax_get_master();
            return View();
        }

        public ActionResult ajax_get_master()
        {
            var data = db.sp_master_table().ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ajax_show_cg()
        {
            var data = db.tb_NEvent_CG.ToList();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        //public ActionResult update_usage_cg(tb_NEvent_CG edit_value)
        //{
        //    string cnnString = System.Configuration.ConfigurationManager.ConnectionStrings["dbinlineEntities2"].ConnectionString;
        //    SqlConnection cnn = new SqlConnection(cnnString);
        //    SqlCommand cmd = new SqlCommand();
        //    cmd.Connection = cnn;
        //    cmd.CommandType = System.Data.CommandType.StoredProcedure;
        //    cmd.CommandText = "sp_add_usage_cg";

inlineStock_rs/Views/InlineStock/Oparate_inline_assy_menu_tablet.cshtml
@{
    ViewBag.Title = "";
}
@*<link rel="stylesheet" href="~/Content/overview-custom.css">*@
<div class="container-fluid">
    <a class="btn btn-sm btn-primary mt-3" href="@Url.Action("Oparate_inline_assy", "InlineStock")">On Website</a>
    <div class="row mt-3">
        <div class="col text-center">
            <h2><b>Please select Material Group</b></h2>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col text-center">
            <button type="button" class="btn btn-lg btn-outline-success my-5 mx-lg-5" id="interposer">INTERPOSER (IP)</button>
            <button type="button" class="btn btn-lg btn-outline-success my-5 mx-lg-5" id="b_frame">B-FRAME</button>
            <button type="button" class="btn btn-lg btn-outline-success my-5 mx-lg-5" id="ffp_frame">FFP FRAME (FRAME)</button>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <button type="button" class="btn btn-lg btn-outline-success my-5 mx-lg-5" id="seal_glass">SEAL GLASS</button>
            <button type="button" class="btn btn-lg btn-outline-success my-5 mx-lg-5" id="resin">RESIN</button>
            <button type="button" class="btn btn-lg btn-outline-success my-5 mx-lg-5" id="capillary">CAPILLARY</button>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <button type="button" class="btn btn-lg btn-outline-success my-5 mx-lg-5" id="gold_wire">GOLD WIRES</button>
        </div>
    </div>

</div>
@*<div class="container-fluid">
        <a class="btn btn-sm btn-outline-primary mt-3" href="@Url.Action("Oparate_inline_assy", "InlineStock")">On Website</a>
        <div class="container-fluid bg-light rounded">
            <div class="h4 font-weight-bold text-center py-3" id="select_option">Select Option</div>
            <div class="row " id="record">
                <div class="col-lg-4 col-sm-6 my-lg-5" id="interposer">
                    <div class="box bg-white shadow border">
                        <div class="d-flex align-items-center">
                            <div class=" text-center d-flex align-items-center justify-content-center"></div>
                            <div class="d-flex flex-column">
                                <b>INTERPOSER (IP)</b>
                                <p class="text-muted">MATERIALS</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 my-lg-0 my-lg-5" id="b_frame">
                    <div class="box bg-white shadow border">
                        <div class="d-flex align-items-center">
                            <div class=" d-flex align-items-center justify-content-center"></div>
                            <div class="d-flex flex-column">
                                <b>B-FRAME</b>
                                <p class="text-muted">MATERIALS</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 my-lg-5" id="ffp_frame">
                    <div class="box bg-white shadow border">
                        <div class="d-flex align-items-center">
                            <div class=" d-flex align-items-center justify-content-center"></div>
                            <div class="d-flex flex-column">
                                <b>FFP FRAME (FRAME)</b>
                                <p class="text-muted">MATERIALS</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-sm-6 my-lg-5" id="seal_glass">
                    <div class="box bg-white shadow border">
                        <div class="d-flex align-items-center">
                            <div class=" d-flex align-items-center justify-content-center"></div>
                            <div class="d-flex flex-column">
                                <b>SEAL GLASS</b>
                                    <p class="text-muted">MATERIALS</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 my-lg-5">
                    <div class="box bg-white shadow border" id="resin">
                        <div class="d-flex align-items-center">
                            <div class=" d-flex align-items-center justify-content-center"></div>
                            <div class="d-flex flex-column">
                                <b>RESIN</b>
                                <p class="text-muted">MATERIALS</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 my-lg-5" id="capillary">
                    <div class="box bg-white shadow border">
                        <div class="d-flex align-items-center">
                            <div class=" d-flex align-items-center justify-content-center"></div>
                            <div class="d-flex flex-column">
                                <b>CAPILLARY</b>
                                <p class="text-muted">MATERIALS</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-sm-6 my-lg-5" id="gold_wire">
                    <div class="box bg-white shadow border">
                        <div class="d-flex align-items-center">
                            <div class=" d-flex align-items-center justify-content-center"></div>
                            <div class="d-flex flex-column">
                                <b>GOLD WIRE</b>
                                <p class="text-muted">MATERIALS</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>*@

<script>

    $(document).ready(function () {

        $("#back").click(function () {
           window.location.href = "@Url.Action("Oparate_inline_assy_tablet", "InlineStock")";
        });

        $("#interposer").click(function () {
            window.location.href = "@Url.Action("record_assy_interposer", "SpRecord")";
        });

        $("#resin").click(function () {
            window.location.href = "@Url.Action("record_assy_resin", "SpRecord")";
        });

        $("#b_frame").click(function () {
            window.location.href = "@Url.Action("record_assy_b_frame", "SpRecord")";
        });

        $("#ffp_frame").click(function () {
            swal({
                title: "Process by auto system!",
                text: "Auto issue and usage by system!",
                icon: "success",
                button: "OK!",
            });
        });

        $("#seal_glass").click(function () {
            window.location.href = "@Url.Action("record_assy_seal_glass", "SpRecord")";
        });

        $("#capillary").click(function () {
            window.location.href = "@Url.Action("record_assy_capillary", "SpRecord")";
        });

        $("#gold_wire").click(function () {
            window.location.href = "@Url.Action("record_assy_gold_wire", "SpRecord")";
        });
    });
</script>

inlineStock_rs/Views/InlineStock/Oparate_inline_assy_tablet.cshtml
@{
    ViewBag.Title = "";
}

<div class="container-fluid">
    <a class="btn btn-sm btn-outline-primary mt-3" href="@Url.Action("Oparate_inline_assy", "InlineStock")">On Website</a>

    <div class="row mt-3">
        <div class="col text-center">
            <button type="button" class="btn btn-lg btn-outline-dark my-3 mx-3" id="topic_record">Usage Inline (เบิกของ)</button>
            <button type="button" class="btn btn-lg btn-outline-dark my-3 mx-3" id="topic_record">Usage Inline (เบิกของ)</button>
            <button type="button" class="btn btn-lg btn-outline-dark my-3 mx-3" id="topic_record">Usage Inline (เบิกของ)</button>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <button type="button" class="btn btn-lg btn-outline-dark my-3 mx-3" id="topic_record">Usage Inline (เบิกของ)</button>
            <button type="button" class="btn btn-lg btn-outline-dark my-3 mx-3" id="topic_record">Usage Inline (เบิกของ)</button>
            <button type="button" class="btn btn-lg btn-outline-dark my-3 mx-3" id="topic_record">Usage Inline (เบิกของ)</button>
        </div>
    </div>
</div>

<!--<div class="container-fluid">
    <a class="btn btn-sm btn-outline-primary mt-3" href="@Url.Action("Oparate_inline_assy", "InlineStock")">On Website</a>
    <div class="col-lg-6 col-sm-6 my-lg-0 my-3" style="margin:0 auto;" >
        <div class="d-flex align-items-center">
            <div class="text-center d-flex align-items-center justify-content-center"></div>
            <button type="button" class="btn btn-lg btn-primary" id="topic_record">Usage Inline (เบิกของ)</button>
        </div>
    </div>-->
    <!--<div class="container bg-light rounded">
    <div class="row">
        <div class="col-lg-6 col-sm-6 my-lg-0 my-3" style="margin:0 auto;" id="topic_record">
            <div class="box bg-white shadow border">
                <div class="d-flex align-items-center">
                    <div class="text-center d-flex align-items-center justify-content-center"></div>
                    <div class="d-flex flex-column">
                        <b>Usage Inline (เบิกของ)</b>
                        <p class="text-muted">MATERIALS</p>
                    </div>
                </div>
            </div>
        </div>
    </div>-->
    <!-- END ROW-->
    <!--</div>-->

<!--</div>-->

<script>
    $(document).ready(function () {
        $("#topic_record").click(function () {
            window.location.href = "@Url.Action("Oparate_inline_assy_menu_tablet", "InlineStock")";
        });

    });
</script>

inlineStock_rs/Views/InlineStock/Oparate_inline_cg_view.cshtml
@{
    ViewBag.Title = "";
}

<style>
    .table th, td {
        color: black;
    }

    .modal-body label {
        color: black;
    }

    td.highlight_max_issue_target {
        background-color: red;
        font-weight: bold;
        color: white;
    }


    td.highlight_7218 {
        background-color: #0094ff;
        color: white;
        font-weight: bold;
    }
</style>

@if (Session["GOALBAL_ID"] != null)
{
    <input type="hidden" value="@Session["GOALBAL_ID"].ToString()" id="temp_user" />
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center border-bottom mt-3">
        <h5 class="ml-1 mr-1" style="color:green;"> NOT OVER TARGET (CG)</h5>
        <h6 class="ml-3"> Last update : @DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss")</h6>
        <a type="button" class="btn btn-sm btn-success" href="@Url.Action("Oparate_inline_cg", "InlineStock")">Open Usage</a>
    </div>
    <div class="table-responsive mt-2">
        <table class="table table-hover table-bordered table-hover" id="table_cg">
            <thead>
                <tr>
                    <th scope="col" style="background-color:royalblue; color:white;">BIZ</th>
                    <th scope="col" style="background-color:royalblue; color:white;">PROCESS</th>
                    <th scope="col" style="background-color:royalblue; color:white;">MATERIAL GROUP</th>
                    <th scope="col" style="background-color:royalblue; color:white;">PART CODE</th>
                    <th scope="col" style="background-color:royalblue; color:white;">MATERIAL NAME</th>
                    <th scope="col" style="background-color:royalblue; color:white;">COST CENTER</th>
                    <th scope="col" style="background-color:royalblue; color:white;">ISSUE W/H</th>
                    <th scope="col" style="background-color:royalblue; color:white;">ISSUE TARGET</th>
                    <th scope="col" style="background-color:royalblue; color:white;">REMAIN INLINE</th>
                    <th scope="col" style="background-color:royalblue; color:white;">UNIT</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center border-bottom mt-2">
        <h5 class="ml-1 mr-1" style="color:red;"> OVER TARGET (CG)</h5>
    </div>
    <div class="table-responsive mt-2 bt-5">
        <table class="table table-bordered table-hover bt-5" id="table_cg_over_target">
            <thead>
                <tr>
                    <th scope="col" style="background-color:royalblue; color:white;">BIZ</th>
                    <th scope="col" style="background-color:royalblue; color:white;">PROCESS</th>
                    <th scope="col" style="background-color:royalblue; color:white;">MATERIAL GROUP</th>
                    <th scope="col" style="background-color:royalblue; color:white;">PART CODE</th>
                    <th scope="col" style="background-color:royalblue; color:white;">MATERIAL NAME</th>
                    <th scope="col" style="background-color:royalblue; color:white;">COST CENTER</th>
                    <th scope="col" style="background-color:royalblue; color:white;">ISSUE W/H</th>
                    <th scope="col" style="background-color:royalblue; color:white;">ISSUE TARGET</th>
                    <th scope="col" style="background-color:royalblue; color:white;">REMAIN INLINE</th>
                    <th scope="col" style="background-color:royalblue; color:white;">UNIT</th>

                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

    <script>
            var temp_user = $('#temp_user').val();
            $(document).ready(function () {
                $("#divError").html("").removeClass("error-msg");
                Create_table_show_cg();
                table_cg_over_target();
                var table = $('#table_cg').DataTable();

                function Create_table_show_cg() {
                    $('#table_cg').DataTable({
                        "destroy": true,
                        "searching": false,
                        "lengthChange": false,
                        "paging": false,
                        "bInfo": false,
                        "stateSave": false,
                        "scrollY": '50vh',
                        "scrollCollapse": true,
                        "lengthChange": false,
                        "ajax": {
                            "type": "POST",
                            "url": "/Material/InlineStock/InlineStock/ajax_show_cg",
                            //"url": "/InlineStock/ajax_show_cg",
                            "datatype": "json"
                        },
                        createdRow: function (node, data) {
                            if (data.hasOwnProperty('ISSUE_WH')) {
                                if (data.ISSUE_WH >= data.ISSUE_TARGET && data.ISSUE_TARGET != 0 ) {
                                    $('td', node).hide();
                                }
                            }
                            if (data.COST_CENTER == '7218') {
                                $('td', node).eq(5).addClass('highlight_7218');
                            }

                        },
                        order: [[ 3, "desc" ]],
                        columnDefs: [
                            {
                                targets: [0, 1, 2, 3, 5, 6, 7, 8, 9], className: 'text-center',
                            },
                            {
                                targets: [6, 7, 8], render: $.fn.dataTable.render.number(',')
                            },
                        ],
                        "columns": [
                                  { data: "BIZ_NAME", "name": "BIZ_NAME", "autoWidth": true },
                                  { data: "PROCESS", "name": "PROCESS", "autoWidth": true },
                                  { data: "MATGROUP", "name": "MATGROUP", "autoWidth": true },
                                  { data: "ITEM_NUMBER", "name": "ITEM_NUMBER", "autoWidth": true },
                                  { data: "MATNAME", "name": "MATNAME", "autoWidth": true },
                                  { data: "COST_CENTER", "name": "COST_CENTER", "autoWidth": true },
                                  { data: "ISSUE_WH", "name": "ISSUE_WH", "autoWidth": true },
                                  { data: "ISSUE_TARGET", "name": "ISSUE_TARGET", "autoWidth": true },
                                  { data: "REMAIN_INLINE", "name": "REMAIN_INLINE", "autoWidth": true },
                                  { data: "UNIT", "name": "UNIT", "autoWidth": true },

                        ], // end columns
                    });
                }

                function table_cg_over_target() {
                    $('#table_cg_over_target').DataTable({
                        "destroy": true,
                        "searching": false,
                        "lengthChange": false,
                        "paging": false,
                        "bInfo": false,
                        "stateSave": false,
                        "scrollY": '50vh',
                        "scrollCollapse": true,
                        "lengthChange": false,
                        "ajax": {
                            "type": "POST",
                            "url": "/Material/InlineStock/InlineStock/ajax_show_cg",
                            //"url": "/InlineStock/ajax_show_cg",
                            "datatype": "json"
                        },
                        createdRow: function (node, data) {
                            if (data.ISSUE_WH <= data.ISSUE_TARGET ) {
                                $('td', node).hide();
                            }
                            if (data.ISSUE_WH >= data.ISSUE_TARGET ) {
                                $('td', node).eq(7).addClass('highlight_max_issue_target');
                                $('td', node).eq(6).addClass('highlight_max_issue_target');
                            }
                            if (data.COST_CENTER == '7218') {
                                $('td', node).eq(5).addClass('highlight_7218');
                            }
                        },
                        order: [[ 3, "desc" ]],
                        columnDefs: [
                               {
                                   targets: [0,1,2,3,5,6,7,8,9], className: 'text-center',
                               },
                             {
                                 targets: [6,7,8] , render: $.fn.dataTable.render.number( ',' )
                             },
                        ],
                        "columns": [
                                  { data: "BIZ_NAME", "name": "BIZ_NAME", "autoWidth": true },
                                  { data: "PROCESS", "name": "PROCESS", "autoWidth": true },
                                  { data: "MATGROUP", "name": "MATGROUP", "autoWidth": true },
                                  { data: "ITEM_NUMBER", "name": "ITEM_NUMBER", "autoWidth": true },
                                  { data: "MATNAME", "name": "MATNAME", "autoWidth": true },
                                  { data: "COST_CENTER", "name": "COST_CENTER", "autoWidth": true },
                                  { data: "ISSUE_WH", "name": "ISSUE_WH", "autoWidth": true },
                                  { data: "ISSUE_TARGET", "name": "ISSUE_TARGET", "autoWidth": true },
                                  { data: "REMAIN_INLINE", "name": "REMAIN_INLINE", "autoWidth": true },
                                  { data: "UNIT", "name": "UNIT", "autoWidth": true },
                        ], // end columns
                    });
                }

            }); @*End Document ready*@
    </script>
}
else
{
    Response.Redirect("~/Login/Login");
}

inlineStock_rs/Views/InlineStock/inline_home.cshtml
@{
    ViewBag.Title = "inline_home";
}